ServerCode/VINMediaCapture/Controllers/ProductDocController.cs
using Microsoft.AspNetCore.Mvc;
using VINMediaCapture.Models;
using VINMediaCapture.Services;
using VINMediaCaptureEntities.Entities;
using System.Diagnostics;
using VINMediaCaptureEntities.ViewModel;
using VINMediaCapture.Service;
using Microsoft.AspNetCore.Mvc.Rendering;
using VINMediaCaptureEntities.Enum;
using System.Reflection;
using System.Net.WebSockets;
using Microsoft.AspNetCore.Hosting.Server;

namespace VINMediaCapture.Controllers
{
    public class ProductDocController : BaseController
    {
        private readonly ILogger<DocTypeItemsController> _logger;
        private readonly IProductDocService _productDocService;
        private readonly IDocTypeItemsService _docTypeItemsService;
        private IWebHostEnvironment _hostingEnvironment;

        public ProductDocController(ILogger<DocTypeItemsController> logger, IDocTypeItemsService docTypeItemsService, IProductDocService productDocService, IWebHostEnvironment hostingEnvironment)
        {
            _logger = logger;
            _docTypeItemsService = docTypeItemsService;
            _productDocService = productDocService;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _productDocService.Index(new ProductDocViewModel());
            var viewBag = await _docTypeItemsService.GetViewBagModel();
            CreateViewBagData(viewBag);
            var fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            data.ToDate = fromDate.AddMonths(1).AddDays(-1).ToString("dd/MM/yyyy");
            data.FromDate = fromDate.ToString("dd/MM/yyyy");
            return View(data);
        }
        public async Task<IActionResult> LoadDetailProduct(string vinCode,int productDoc,int docType)
        {
            var data = await _productDocService.LoadDetailProductDoc(vinCode, productDoc, docType);
            return PartialView(@"~/Views/ProductDoc/DetailProductDoc.cshtml", data);
        }
        [HttpPost]
        public async Task<IActionResult> Index(ProductDocViewModel model)
        {
            var viewBag = await _docTypeItemsService.GetViewBagModel();
            CreateViewBagData(viewBag);
            var data= await _productDocService.Index(model);
            model.ProductDocInfos = data.ProductDocInfos;
            model.TotalRecord = data.TotalRecord;
            return View(model);
        }
        public void CreateViewBagData(ViewBagDropDownModelModel docTypeItemsViewModel)
        {
            ViewBag.Color = docTypeItemsViewModel.Colors;
            ViewBag.Model = docTypeItemsViewModel.Models;
            ViewBag.Market = docTypeItemsViewModel.Markets;
            ViewBag.DocTypes = docTypeItemsViewModel.DocTypes;
            var attrDataTypes = new List<SelectListItem>();
            attrDataTypes.Add(new SelectListItem { Value=((int)EAttrDataType.VARCHAR).ToString(),Text= EAttrDataType.VARCHAR.GetDescription()});
            attrDataTypes.Add(new SelectListItem { Value = ((int)EAttrDataType.INTEGER).ToString(), Text = EAttrDataType.INTEGER.GetDescription() });
            attrDataTypes.Add(new SelectListItem { Value = ((int)EAttrDataType.BOOLEAN).ToString(), Text = EAttrDataType.BOOLEAN.GetDescription() });
            attrDataTypes.Add(new SelectListItem { Value = ((int)EAttrDataType.DATE).ToString(), Text = EAttrDataType.DATE.GetDescription() });
            attrDataTypes.Add(new SelectListItem { Value = ((int)EAttrDataType.FLOAT).ToString(), Text = EAttrDataType.FLOAT.GetDescription() });
            attrDataTypes.Add(new SelectListItem { Value = ((int)EAttrDataType.IMGCAPT).ToString(), Text = EAttrDataType.IMGCAPT.GetDescription() });
            ViewBag.AttrDataTypes = attrDataTypes;
            //attrDataTypes.Add(new SelectListItem { Value = ((int)EAttrDataType.DATFILE).ToString(), Text = EAttrDataType.DATFILE.GetDescription() });

        }
        public FileResult Download(string url)
        {
            var path = _hostingEnvironment.WebRootPath+ url;
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = Path.GetFileName(path);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

ServerCode/VINMediaCapture/Views/ProductDoc/DetailProductDoc.cshtml
@using VINMediaCaptureEntities.Enum
@using VINMediaCaptureEntities.ViewModel
@model DetailProductDocModel

@if (String.IsNullOrEmpty(Model.Model.ModelName) && String.IsNullOrEmpty(Model.Market.MarketCode) && String.IsNullOrEmpty(Model.Color.ColorCode))
{
    <h2>@(String.Format("{0}", Model.Vincode))</h2>
}
else
{
    <h2>@(String.Format("{0} - {1} -{2}", Model.Model.ModelName, String.Format("{0}{1}{2}", Model.Model.ModelCode, Model.Market.MarketCode, Model.Color.ColorCode), Model.Vincode))</h2>
}

<table class="table table-bordered">
    <thead>
    <th>Tên thuộc tính</th>
        @{
            if (Model.DocType == (int)EDocType.ThuThapQC)
            {
            <th>Kiểu dữ liệu</th>
            }
        }

    <th>Giá trị</th>
    </thead>
    <tbody id="tbodyModels">
        @{
            if (Model.DocType == (int)EDocType.ThuThapQC)
            {
                if (Model.ProductDocValInfo == null || !Model.ProductDocValInfo.Any())
                {
                <td colspan="3">Không có dữ liệu</td>
                }
                else
                {
                    foreach (var item in Model.ProductDocValInfo)
                    {
                    <tr>
                        <td>@item.DocTypeItem.ItemName</td>
                        <td>@(((EAttrDataType)item.DocTypeItemAttr.AttrDataType).GetDescription())</td>
                        <td>
                                @{
                                    if (item.DocTypeItemAttr.AttrDataType == (int)EAttrDataType.IMGCAPT)
                                    {
                                    <a href="@Url.Action("Download","ProductDoc", new{url=item.ProductDocVal.AttrValue})"><img src="@item.ProductDocVal.AttrValue" style="width:100px" /></a>
                                    }
                                    else if (item.DocTypeItemAttr.AttrDataType == (int)EAttrDataType.BOOLEAN)
                                    {
                                    <label>@item.ProductDocVal.AttrValue</label>
                                    }
                                    else
                                    {
                                    <label>@item.ProductDocVal.AttrValue</label>
                                    }
                                }
                        </td>
                    </tr>
                    }
                }
            }
            else
            {
                if (Model.ProductDocValInfo == null || !Model.ProductDocValInfo.Any())
                {
                <td colspan="2">Không có dữ liệu</td>
                }
                else
                {
                    foreach (var item in Model.ProductDocValInfo)
                    {
                    <tr>
                        <td>@item.DocTypeItem.ItemName</td>
                        <td>

                                @{
                                    if (System.IO.Path.GetExtension(item.ProductDocVal.AttrValue).ToLower() == ".pdf")
                                    {
                                    <a target="_blank" href="/pdfviewer/web/viewer.html?file=@item.ProductDocVal.AttrValue"><i class="fa fa-eye"></i></a>
                                    <a href="@Url.Action("Download","ProductDoc", new{url=item.ProductDocVal.AttrValue})"><i class="fa fa-download"></i></a>
                                    }
                                    else
                                    {
                                    <a href="@Url.Action("Download","ProductDoc", new{url=item.ProductDocVal.AttrValue})"><img src="@item.ProductDocVal.AttrValue" style="width:100px" /></a>
                                    }

                                }
                        </td>
                    </tr>
                    }
                }
            }
        }
    </tbody>